### ISSUE TITLE
Next level when you hit the goal

### ISSUE THREAD

**Issue by sionleroux** [sinisterstuf/cr1ckt#5]

**Comment by Thesryn** [comment]
Acros and I would prefer the game to be one big well made level instead of many wack small ones, so maybe this will be redundant. At least there is an entity that represents the end...

**Comment by sionleroux** [comment]
Ok, this was too easy to implement (7 lines of code) so I did it. Landing on the exit now advances you to the next level. The logic can be changed to anything else later.
