### ISSUE TITLE
Jump directionally with A/D instead of flipping each jump

### ISSUE THREAD

**Issue by sionleroux** [sinisterstuf/cr1ckt#7]
Currently the only control is space, that jumps in the direction you're facing and you switch directions when you land.

Things to consider:

- should space still do anything?
- also include arrow keys as a possibliity?
- how will touch screen input work?
- what about mouse support, which would've so far just been a click?

**Comment by Thesryn** [comment]
Hmmm ok, we'll have space not do anything
Then when you tap
D the cricket turns to face right powers up and jumps when you let go (vice versa for a)

Think about arrow keys and touch screen later, it's easy enough...but I don't care about it right now

**Comment by sionleroux** [comment]
What if someone presses A and D both at the same time?
