### ISSUE TITLE
Get the screen to follow the cricket

### ISSUE THREAD

**Issue by Thesryn** [sinisterstuf/cr1ckt#9]
So that I can try to make a big level.
The visible screen can maybe be the same size as what a level is now, or a little smaller
It might be cool to level that is 4 or 8 times the size

**Comment by sionleroux** [comment]
Ok, this requires implementing an independent camera, I haven't done that before, I'll read up about it first

**Comment by sionleroux** [comment]
- Draw everything of the world, cricket, - background, entities to a separate "off-screen" Ebiten image.
- Take a sub-image of that with dimensions of screen size and position half screen size minus from current cricket location
- Draw the blackness onto that
- Draw that onto the screen
